# coding: utf-8

"""
    Rvvup API

    Rvvup Public API

    The version of the OpenAPI document: 2024-03-01
    Contact: info@rvvup.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.payment_settlement_status import PaymentSettlementStatus

class TestPaymentSettlementStatus(unittest.TestCase):
    """PaymentSettlementStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentSettlementStatus(self):
        """Test PaymentSettlementStatus"""
        # inst = PaymentSettlementStatus()

if __name__ == '__main__':
    unittest.main()
