# coding: utf-8

"""
    Rvvup API

    Rvvup Public API

    The version of the OpenAPI document: 2024-03-01
    Contact: info@rvvup.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.statement_export_request import StatementExportRequest

class TestStatementExportRequest(unittest.TestCase):
    """StatementExportRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatementExportRequest:
        """Test StatementExportRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatementExportRequest`
        """
        model = StatementExportRequest()
        if include_optional:
            return StatementExportRequest(
                disbursement_batch_id = '',
                export_format = 'OFX_V2',
                range = openapi_client.models.start_end.StartEnd(
                    end = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return StatementExportRequest(
                export_format = 'OFX_V2',
        )
        """

    def testStatementExportRequest(self):
        """Test StatementExportRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
