# coding: utf-8

"""
    Rvvup API

    Rvvup Public API

    The version of the OpenAPI document: 2024-03-01
    Contact: info@rvvup.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.payment_method_status import PaymentMethodStatus

class TestPaymentMethodStatus(unittest.TestCase):
    """PaymentMethodStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentMethodStatus(self):
        """Test PaymentMethodStatus"""
        # inst = PaymentMethodStatus()

if __name__ == '__main__':
    unittest.main()
