# coding: utf-8

"""
    Rvvup API

    Rvvup Public API

    The version of the OpenAPI document: 2024-03-01
    Contact: info@rvvup.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.payment_method_asset import PaymentMethodAsset

class TestPaymentMethodAsset(unittest.TestCase):
    """PaymentMethodAsset unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentMethodAsset:
        """Test PaymentMethodAsset
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentMethodAsset`
        """
        model = PaymentMethodAsset()
        if include_optional:
            return PaymentMethodAsset(
                asset_type = 'SCRIPT',
                attributes = {
                    'key' : ''
                    },
                url = ''
            )
        else:
            return PaymentMethodAsset(
                asset_type = 'SCRIPT',
                attributes = {
                    'key' : ''
                    },
                url = '',
        )
        """

    def testPaymentMethodAsset(self):
        """Test PaymentMethodAsset"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
