# coding: utf-8

"""
    Rvvup API

    Rvvup Public API

    The version of the OpenAPI document: 2024-03-01
    Contact: info@rvvup.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.checkout_template import CheckoutTemplate

class TestCheckoutTemplate(unittest.TestCase):
    """CheckoutTemplate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CheckoutTemplate:
        """Test CheckoutTemplate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CheckoutTemplate`
        """
        model = CheckoutTemplate()
        if include_optional:
            return CheckoutTemplate(
                amount_type = 'FIXED',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                customer_fields = openapi_client.models.checkout_customer_fields.CheckoutCustomerFields(
                    optional = [
                        'GIVEN_NAME'
                        ], 
                    required = [
                        'GIVEN_NAME'
                        ], ),
                enabled_payment_methods = [
                    'FAKE_PAYMENT_METHOD'
                    ],
                id = '',
                merchant_id = '',
                name = '',
                notify_customer = True,
                notify_merchant = True,
                payment_method_settings = openapi_client.models.checkout_payment_method_settings.CheckoutPaymentMethodSettings(
                    apple_pay = openapi_client.models.checkout_apple_pay_settings.CheckoutApplePaySettings(
                        capture_type = 'AUTOMATIC_CHECKOUT', 
                        customer_fields = openapi_client.models.checkout_customer_fields.CheckoutCustomerFields(
                            optional = [
                                'GIVEN_NAME'
                                ], 
                            required = [
                                'GIVEN_NAME'
                                ], ), ), 
                    card = openapi_client.models.checkout_card_settings.CheckoutCardSettings(), 
                    pay_by_bank = openapi_client.models.checkout_pay_by_bank_settings.CheckoutPayByBankSettings(), ),
                source = 'API',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return CheckoutTemplate(
                amount_type = 'FIXED',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                merchant_id = '',
                name = '',
                notify_customer = True,
                notify_merchant = True,
                source = 'API',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testCheckoutTemplate(self):
        """Test CheckoutTemplate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
