# coding: utf-8

"""
    Rvvup API

    Rvvup Public API

    The version of the OpenAPI document: 2024-03-01
    Contact: info@rvvup.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.statement_exports_api import StatementExportsApi


class TestStatementExportsApi(unittest.TestCase):
    """StatementExportsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StatementExportsApi()

    def tearDown(self) -> None:
        pass

    def test_export_statement(self) -> None:
        """Test case for export_statement

        Export a statement
        """
        pass


if __name__ == '__main__':
    unittest.main()
