# coding: utf-8

"""
    Rvvup API

    Rvvup Public API

    The version of the OpenAPI document: 2024-03-01
    Contact: info@rvvup.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.payment_links_api import PaymentLinksApi


class TestPaymentLinksApi(unittest.TestCase):
    """PaymentLinksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PaymentLinksApi()

    def tearDown(self) -> None:
        pass

    def test_create_payment_link(self) -> None:
        """Test case for create_payment_link

        Create new payment link
        """
        pass

    def test_deactivate_payment_link(self) -> None:
        """Test case for deactivate_payment_link

        Deactivate a payment link
        """
        pass

    def test_get_payment_link(self) -> None:
        """Test case for get_payment_link

        Get a payment link
        """
        pass

    def test_list_payment_links(self) -> None:
        """Test case for list_payment_links

        List payment links
        """
        pass


if __name__ == '__main__':
    unittest.main()
