# coding: utf-8

"""
    Rvvup API

    Rvvup Public API

    The version of the OpenAPI document: 2024-03-01
    Contact: info@rvvup.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.item_restriction import ItemRestriction

class TestItemRestriction(unittest.TestCase):
    """ItemRestriction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testItemRestriction(self):
        """Test ItemRestriction"""
        # inst = ItemRestriction()

if __name__ == '__main__':
    unittest.main()
