# coding: utf-8

"""
    Rvvup API

    Rvvup Public API

    The version of the OpenAPI document: 2024-03-01
    Contact: info@rvvup.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.customer_input import CustomerInput

class TestCustomerInput(unittest.TestCase):
    """CustomerInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomerInput:
        """Test CustomerInput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomerInput`
        """
        model = CustomerInput()
        if include_optional:
            return CustomerInput(
                email = '0',
                given_name = 'John',
                phone_number = '0',
                surname = 'Doe'
            )
        else:
            return CustomerInput(
        )
        """

    def testCustomerInput(self):
        """Test CustomerInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
