# coding: utf-8

"""
    Rvvup API

    Rvvup Public API

    The version of the OpenAPI document: 2024-03-01
    Contact: info@rvvup.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.payment_status import PaymentStatus

class TestPaymentStatus(unittest.TestCase):
    """PaymentStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentStatus(self):
        """Test PaymentStatus"""
        # inst = PaymentStatus()

if __name__ == '__main__':
    unittest.main()
