# coding: utf-8

"""
    Rvvup API

    Rvvup Public API

    The version of the OpenAPI document: 2024-03-01
    Contact: info@rvvup.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.webhook_update_input import WebhookUpdateInput

class TestWebhookUpdateInput(unittest.TestCase):
    """WebhookUpdateInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebhookUpdateInput:
        """Test WebhookUpdateInput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebhookUpdateInput`
        """
        model = WebhookUpdateInput()
        if include_optional:
            return WebhookUpdateInput(
                headers = {
                    'key' : ''
                    },
                status = 'ENABLED',
                subscribed_events = ["PAYMENT_SUCCEEDED"],
                url = 'https://example.com/new/webhook'
            )
        else:
            return WebhookUpdateInput(
        )
        """

    def testWebhookUpdateInput(self):
        """Test WebhookUpdateInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
