# coding: utf-8

"""
    Rvvup API

    Rvvup Public API

    The version of the OpenAPI document: 2024-03-01
    Contact: info@rvvup.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.checkout_customer_fields_input import CheckoutCustomerFieldsInput

class TestCheckoutCustomerFieldsInput(unittest.TestCase):
    """CheckoutCustomerFieldsInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CheckoutCustomerFieldsInput:
        """Test CheckoutCustomerFieldsInput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CheckoutCustomerFieldsInput`
        """
        model = CheckoutCustomerFieldsInput()
        if include_optional:
            return CheckoutCustomerFieldsInput(
                optional = [
                    'GIVEN_NAME'
                    ],
                required = [
                    'GIVEN_NAME'
                    ]
            )
        else:
            return CheckoutCustomerFieldsInput(
        )
        """

    def testCheckoutCustomerFieldsInput(self):
        """Test CheckoutCustomerFieldsInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
