# coding: utf-8

"""
    Rvvup API

    Rvvup Public API

    The version of the OpenAPI document: 2024-03-01
    Contact: info@rvvup.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.payment_method_settings import PaymentMethodSettings

class TestPaymentMethodSettings(unittest.TestCase):
    """PaymentMethodSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentMethodSettings:
        """Test PaymentMethodSettings
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentMethodSettings`
        """
        model = PaymentMethodSettings()
        if include_optional:
            return PaymentMethodSettings(
                assets = [
                    openapi_client.models.payment_method_asset.PaymentMethodAsset(
                        asset_type = 'SCRIPT', 
                        attributes = {
                            'key' : ''
                            }, 
                        url = '', )
                    ],
                description = '',
                display_name = ''
            )
        else:
            return PaymentMethodSettings(
                assets = [
                    openapi_client.models.payment_method_asset.PaymentMethodAsset(
                        asset_type = 'SCRIPT', 
                        attributes = {
                            'key' : ''
                            }, 
                        url = '', )
                    ],
                description = '',
                display_name = '',
        )
        """

    def testPaymentMethodSettings(self):
        """Test PaymentMethodSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
