# coding: utf-8

"""
    Rvvup API

    Rvvup Public API

    The version of the OpenAPI document: 2024-03-01
    Contact: info@rvvup.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.payment_action import PaymentAction

class TestPaymentAction(unittest.TestCase):
    """PaymentAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentAction:
        """Test PaymentAction
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentAction`
        """
        model = PaymentAction()
        if include_optional:
            return PaymentAction(
                method = 'REDIRECT_URL',
                type = 'AUTHORIZATION',
                value = ''
            )
        else:
            return PaymentAction(
                method = 'REDIRECT_URL',
                type = 'AUTHORIZATION',
                value = '',
        )
        """

    def testPaymentAction(self):
        """Test PaymentAction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
