# coding: utf-8

"""
    Rvvup API

    Rvvup Public API

    The version of the OpenAPI document: 2024-03-01
    Contact: info@rvvup.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.checkout_templates_api import CheckoutTemplatesApi


class TestCheckoutTemplatesApi(unittest.TestCase):
    """CheckoutTemplatesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CheckoutTemplatesApi()

    def tearDown(self) -> None:
        pass

    def test_create_checkout_template(self) -> None:
        """Test case for create_checkout_template

        Create new checkout template
        """
        pass

    def test_get_checkout_template(self) -> None:
        """Test case for get_checkout_template

        Get a checkout template
        """
        pass

    def test_list_checkout_templates(self) -> None:
        """Test case for list_checkout_templates

        List checkout templates
        """
        pass

    def test_update_checkout_template(self) -> None:
        """Test case for update_checkout_template

        Update a checkout template
        """
        pass


if __name__ == '__main__':
    unittest.main()
