# coding: utf-8

"""
    Rvvup API

    Rvvup Public API

    The version of the OpenAPI document: 2024-03-01
    Contact: info@rvvup.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.payment_summary import PaymentSummary

class TestPaymentSummary(unittest.TestCase):
    """PaymentSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentSummary:
        """Test PaymentSummary
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentSummary`
        """
        model = PaymentSummary()
        if include_optional:
            return PaymentSummary(
                is_manually_capturable = True,
                is_refundable = True,
                is_voidable = True,
                payment_actions = [
                    openapi_client.models.payment_action.PaymentAction(
                        method = 'REDIRECT_URL', 
                        type = 'AUTHORIZATION', 
                        value = '', )
                    ],
                refundable_amount = openapi_client.models.money.Money(
                    amount = '', 
                    currency = '', )
            )
        else:
            return PaymentSummary(
                is_manually_capturable = True,
                is_refundable = True,
                is_voidable = True,
                payment_actions = [
                    openapi_client.models.payment_action.PaymentAction(
                        method = 'REDIRECT_URL', 
                        type = 'AUTHORIZATION', 
                        value = '', )
                    ],
                refundable_amount = openapi_client.models.money.Money(
                    amount = '', 
                    currency = '', ),
        )
        """

    def testPaymentSummary(self):
        """Test PaymentSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
