# coding: utf-8

"""
    Rvvup API

    Rvvup Public API

    The version of the OpenAPI document: 2024-03-01
    Contact: info@rvvup.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.checkout_payment_method_settings import CheckoutPaymentMethodSettings

class TestCheckoutPaymentMethodSettings(unittest.TestCase):
    """CheckoutPaymentMethodSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CheckoutPaymentMethodSettings:
        """Test CheckoutPaymentMethodSettings
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CheckoutPaymentMethodSettings`
        """
        model = CheckoutPaymentMethodSettings()
        if include_optional:
            return CheckoutPaymentMethodSettings(
                apple_pay = openapi_client.models.checkout_apple_pay_settings.CheckoutApplePaySettings(
                    capture_type = 'AUTOMATIC_CHECKOUT', 
                    customer_fields = openapi_client.models.checkout_customer_fields.CheckoutCustomerFields(
                        optional = [
                            'GIVEN_NAME'
                            ], 
                        required = [
                            'GIVEN_NAME'
                            ], ), ),
                card = openapi_client.models.checkout_card_settings.CheckoutCardSettings(
                    capture_type = 'AUTOMATIC_CHECKOUT', 
                    customer_fields = openapi_client.models.checkout_customer_fields.CheckoutCustomerFields(
                        optional = [
                            'GIVEN_NAME'
                            ], 
                        required = [
                            'GIVEN_NAME'
                            ], ), ),
                pay_by_bank = openapi_client.models.checkout_pay_by_bank_settings.CheckoutPayByBankSettings(
                    capture_type = 'AUTOMATIC_CHECKOUT', 
                    customer_fields = openapi_client.models.checkout_customer_fields.CheckoutCustomerFields(
                        optional = [
                            'GIVEN_NAME'
                            ], 
                        required = [
                            'GIVEN_NAME'
                            ], ), )
            )
        else:
            return CheckoutPaymentMethodSettings(
        )
        """

    def testCheckoutPaymentMethodSettings(self):
        """Test CheckoutPaymentMethodSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
