# coding: utf-8

"""
    Rvvup API

    Rvvup Public API

    The version of the OpenAPI document: 2024-03-01
    Contact: info@rvvup.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.checkout_customer_field_type import CheckoutCustomerFieldType

class TestCheckoutCustomerFieldType(unittest.TestCase):
    """CheckoutCustomerFieldType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCheckoutCustomerFieldType(self):
        """Test CheckoutCustomerFieldType"""
        # inst = CheckoutCustomerFieldType()

if __name__ == '__main__':
    unittest.main()
