# coding: utf-8

"""
    Rvvup API

    Rvvup Public API

    The version of the OpenAPI document: 2024-03-01
    Contact: info@rvvup.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.payment_sessions_api import PaymentSessionsApi


class TestPaymentSessionsApi(unittest.TestCase):
    """PaymentSessionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PaymentSessionsApi()

    def tearDown(self) -> None:
        pass

    def test_create_payment_session(self) -> None:
        """Test case for create_payment_session

        Create a payment session
        """
        pass

    def test_get_payment_session(self) -> None:
        """Test case for get_payment_session

        Get a payment session
        """
        pass


if __name__ == '__main__':
    unittest.main()
