# coding: utf-8

"""
    Rvvup API

    Rvvup Public API

    The version of the OpenAPI document: 2024-03-01
    Contact: info@rvvup.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.checkout_card_settings import CheckoutCardSettings

class TestCheckoutCardSettings(unittest.TestCase):
    """CheckoutCardSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CheckoutCardSettings:
        """Test CheckoutCardSettings
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CheckoutCardSettings`
        """
        model = CheckoutCardSettings()
        if include_optional:
            return CheckoutCardSettings(
                capture_type = 'AUTOMATIC_CHECKOUT',
                customer_fields = openapi_client.models.checkout_customer_fields.CheckoutCustomerFields(
                    optional = [
                        'GIVEN_NAME'
                        ], 
                    required = [
                        'GIVEN_NAME'
                        ], )
            )
        else:
            return CheckoutCardSettings(
        )
        """

    def testCheckoutCardSettings(self):
        """Test CheckoutCardSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
