# coding: utf-8

"""
    Rvvup API

    Rvvup Public API

    The version of the OpenAPI document: 2024-03-01
    Contact: info@rvvup.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.item_input import ItemInput

class TestItemInput(unittest.TestCase):
    """ItemInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ItemInput:
        """Test ItemInput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ItemInput`
        """
        model = ItemInput()
        if include_optional:
            return ItemInput(
                name = '0',
                price = {"amount":"100.00","currency":"GBP"},
                price_with_tax = {"amount":"100.00","currency":"GBP"},
                quantity = '',
                restriction = 'ALLOWED',
                sku = '0',
                tax = {"amount":"100.00","currency":"GBP"},
                total = {"amount":"100.00","currency":"GBP"}
            )
        else:
            return ItemInput(
                name = '0',
                price = {"amount":"100.00","currency":"GBP"},
                quantity = '',
                sku = '0',
                total = {"amount":"100.00","currency":"GBP"},
        )
        """

    def testItemInput(self):
        """Test ItemInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
