# coding: utf-8

"""
    Rvvup API

    Rvvup Public API

    The version of the OpenAPI document: 2024-03-01
    Contact: info@rvvup.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.address_input import AddressInput

class TestAddressInput(unittest.TestCase):
    """AddressInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddressInput:
        """Test AddressInput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddressInput`
        """
        model = AddressInput()
        if include_optional:
            return AddressInput(
                city = 'London',
                company = '0',
                country_code = 'GB',
                line1 = '10 Downing Street',
                line2 = 'Westminster',
                name = 'John Doe',
                phone_number = '0',
                postcode = 'SW1A 2AA',
                state = 'Greater London'
            )
        else:
            return AddressInput(
                city = 'London',
                country_code = 'GB',
                line1 = '10 Downing Street',
                name = 'John Doe',
                postcode = 'SW1A 2AA',
        )
        """

    def testAddressInput(self):
        """Test AddressInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
