# coding: utf-8

"""
    Rvvup API

    Rvvup Public API

    The version of the OpenAPI document: 2024-03-01
    Contact: info@rvvup.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ApplicationSource(str, Enum):
    """
    The source of the application.
    """

    """
    allowed enum values
    """
    API = 'API'
    XERO = 'XERO'
    MOTO = 'MOTO'
    DASHBOARD_MOTO = 'DASHBOARD_MOTO'
    DASHBOARD_PAYMENT_LINK = 'DASHBOARD_PAYMENT_LINK'
    MAGENTO_MOTO = 'MAGENTO_MOTO'
    MAGENTO_PAYMENT_LINK = 'MAGENTO_PAYMENT_LINK'
    PAY_NOW_IN_PERSON = 'PAY_NOW_IN_PERSON'
    PAY_NOW_MOTO = 'PAY_NOW_MOTO'
    PAY_NOW_PAYMENT_LINK = 'PAY_NOW_PAYMENT_LINK'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ApplicationSource from a JSON string"""
        return cls(json.loads(json_str))


