# coding: utf-8

"""
    Rvvup API

    Rvvup Public API

    The version of the OpenAPI document: 2024-03-01
    Contact: info@rvvup.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CheckoutCustomerFieldType(str, Enum):
    """
    The customer field type.
    """

    """
    allowed enum values
    """
    GIVEN_NAME = 'GIVEN_NAME'
    SURNAME = 'SURNAME'
    EMAIL = 'EMAIL'
    PHONE_NUMBER = 'PHONE_NUMBER'
    BILLING_ADDRESS = 'BILLING_ADDRESS'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CheckoutCustomerFieldType from a JSON string"""
        return cls(json.loads(json_str))


