# coding: utf-8

"""
    Rvvup API

    Rvvup Public API

    The version of the OpenAPI document: 2024-03-01
    Contact: info@rvvup.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CheckoutAmountType(str, Enum):
    """
    The amount type for the checkout. This can be either a fixed amount or an editable amount. If the amount is editable, the user can enter the amount they want to pay inside the hosted checkout. If the amount is fixed, the amount set in the checkout is the amount that will be paid and cannot be changed inside the hosted checkout.
    """

    """
    allowed enum values
    """
    FIXED = 'FIXED'
    EDITABLE = 'EDITABLE'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CheckoutAmountType from a JSON string"""
        return cls(json.loads(json_str))


