# coding: utf-8

"""
    Rvvup API

    Rvvup Public API

    The version of the OpenAPI document: 2024-03-01
    Contact: info@rvvup.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_client.models.item_restriction import ItemRestriction
from openapi_client.models.money_input import MoneyInput
from typing import Optional, Set
from typing_extensions import Self

class ItemInput(BaseModel):
    """
    An item that the customer is purchasing.
    """ # noqa: E501
    name: Annotated[str, Field(min_length=1, strict=True, max_length=255)] = Field(description="The name of the item.")
    price: MoneyInput
    price_with_tax: Optional[MoneyInput] = Field(default=None, alias="priceWithTax")
    quantity: StrictStr = Field(description="The quantity of the item being purchased.")
    restriction: Optional[ItemRestriction] = None
    sku: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(description="Stock keeping unit - the unique identifier for the item.")
    tax: Optional[MoneyInput] = None
    total: MoneyInput
    __properties: ClassVar[List[str]] = ["name", "price", "priceWithTax", "quantity", "restriction", "sku", "tax", "total"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ItemInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of price
        if self.price:
            _dict['price'] = self.price.to_dict()
        # override the default output from pydantic by calling `to_dict()` of price_with_tax
        if self.price_with_tax:
            _dict['priceWithTax'] = self.price_with_tax.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tax
        if self.tax:
            _dict['tax'] = self.tax.to_dict()
        # override the default output from pydantic by calling `to_dict()` of total
        if self.total:
            _dict['total'] = self.total.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ItemInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "price": MoneyInput.from_dict(obj["price"]) if obj.get("price") is not None else None,
            "priceWithTax": MoneyInput.from_dict(obj["priceWithTax"]) if obj.get("priceWithTax") is not None else None,
            "quantity": obj.get("quantity"),
            "restriction": obj.get("restriction"),
            "sku": obj.get("sku"),
            "tax": MoneyInput.from_dict(obj["tax"]) if obj.get("tax") is not None else None,
            "total": MoneyInput.from_dict(obj["total"]) if obj.get("total") is not None else None
        })
        return _obj


