# coding: utf-8

"""
    Rvvup API

    Rvvup Public API

    The version of the OpenAPI document: 2024-03-01
    Contact: info@rvvup.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PaymentDeclineReason(str, Enum):
    """
    The reason the payment was declined.
    """

    """
    allowed enum values
    """
    INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS'
    FUNDING_INSTRUMENT_DECLINED = 'FUNDING_INSTRUMENT_DECLINED'
    CONSENT_MISSING = 'CONSENT_MISSING'
    SUSPECTED_FRAUD = 'SUSPECTED_FRAUD'
    AMOUNT_LIMITS_EXCEEDED = 'AMOUNT_LIMITS_EXCEEDED'
    ACCOUNT_CLOSED = 'ACCOUNT_CLOSED'
    CVV2_FAILURE = 'CVV2_FAILURE'
    FUNDING_INSTRUMENT_EXPIRED = 'FUNDING_INSTRUMENT_EXPIRED'
    FUNDING_INSTRUMENT_INVALID = 'FUNDING_INSTRUMENT_INVALID'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PaymentDeclineReason from a JSON string"""
        return cls(json.loads(json_str))


