# coding: utf-8

"""
    Rvvup API

    Rvvup Public API

    The version of the OpenAPI document: 2024-03-01
    Contact: info@rvvup.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PaymentMethod(str, Enum):
    """
    The payment method.
    """

    """
    allowed enum values
    """
    FAKE_PAYMENT_METHOD = 'FAKE_PAYMENT_METHOD'
    CLEARPAY = 'CLEARPAY'
    CRYPTO = 'CRYPTO'
    PAYPAL = 'PAYPAL'
    PAYPAL_CUSTOM_CARD = 'PAYPAL_CUSTOM_CARD'
    CARD = 'CARD'
    APPLE_PAY = 'APPLE_PAY'
    PAY_BY_BANK = 'PAY_BY_BANK'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PaymentMethod from a JSON string"""
        return cls(json.loads(json_str))


