# coding: utf-8

"""
    Rvvup API

    Rvvup Public API

    The version of the OpenAPI document: 2024-03-01
    Contact: info@rvvup.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PaymentStatus(str, Enum):
    """
    The status of the payment.
    """

    """
    allowed enum values
    """
    CREATED = 'CREATED'
    PENDING = 'PENDING'
    SUCCEEDED = 'SUCCEEDED'
    REQUIRES_ACTION = 'REQUIRES_ACTION'
    FAILED = 'FAILED'
    CANCELLED = 'CANCELLED'
    DECLINED = 'DECLINED'
    EXPIRED = 'EXPIRED'
    VOIDED = 'VOIDED'
    AUTHORIZED = 'AUTHORIZED'
    AUTHORIZATION_EXPIRED = 'AUTHORIZATION_EXPIRED'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PaymentStatus from a JSON string"""
        return cls(json.loads(json_str))


